version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 18
  build:
    commands:
      - npm install time
      - export BUCKET=spike-lambda-codepipeline
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  files:
    - template.yaml
    - outputtemplate.yaml
